# Generated by Django 2.0.5 on 2018-10-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msa_app', '0002_auto_20181018_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='referee_comments',
            field=models.TextField(),
        ),
    ]
