# Generated by Django 2.0.5 on 2018-11-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msa_app', '0004_auto_20181021_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, upload_to='team-logo/'),
        ),
        migrations.AlterField(
            model_name='match',
            name='guest_team_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='referee_comments',
            field=models.TextField(null=True),
        ),
    ]
