# Generated by Django 2.0.5 on 2018-11-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msa_app', '0005_auto_20181110_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msarole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Coach', 'Coach'), ('Referee', 'Referee')], max_length=20)),
                ('receiver_name', models.CharField(max_length=10)),
                ('receiver_email', models.EmailField(max_length=100)),
                ('registered', models.CharField(default='No', max_length=10)),
            ],
        ),
    ]
