# Generated by Django 2.0.5 on 2018-11-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msa_app', '0006_msarole'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_logo_url',
            field=models.TextField(default='https://ibb.co/hj3G9f', null=True),
        ),
    ]
