# Generated by Django 2.0.5 on 2018-11-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msa_app', '0007_team_team_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_logo_url',
            field=models.CharField(default='https://ibb.co/hj3G9f', max_length=510, null=True),
        ),
    ]
