# Generated by Django 2.0.5 on 2018-11-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msa_app', '0008_auto_20181117_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_logo',
        ),
        migrations.AlterField(
            model_name='team',
            name='team_logo_url',
            field=models.CharField(default='https://image.ibb.co/miF7FL/default-image.jpg', max_length=510, null=True),
        ),
    ]
